languageCode = 'en-us'
title = 'uug4na'

[module]
  [[module.imports]]
    path = "github.com/lordmathis/hugo-theme-nightfall"

[params]
  user = "uug4na"
  hostname = "github.io"
  openLinksInNewTab = true
  displayDateFormat = "2006-01-02"
  sitedescription = "Security • CTF • Engineering"

  [params.author]
    name = ""
    email = "uug4na@gmail.com"

  [params.styles]
    color = "blue" 

[menu]
  [[menu.header]]
    name = "posts"
    url  = "/posts"
    weight = 0
  [[menu.header]]
    name = "about"
    url  = "/about/"
    weight = 1

[pagination]
  pagerSize = 10
